### ISSUE TITLE
How to handle OSError when the USB host is unable to accept a report?

### ISSUE THREAD

**Issue by jamesra** [fasteddy516/CircuitPython_JoystickXL#16]
Our first attempt to use this library had a strange incompatibility between the ESP32S2 board and the old HP laptops at the high school where about 50% of the time the computer would not recognize the USB device as a joystick.   Most other computer hosts worked 90% to 100% of the time but would fail within a minute.  We never understood the underlying cause on the ESP32S2 and moving to a different feather board (whose model number is now covered by a soldered PCB) solved the problem.

In all cases what we found was joystick_xl's call to `self._device.send_report` in joystick.py#259 raised an OSError exception ("USB Busy") that killed CircuitPython.  Wrapping that call in a try/except block allowed the systems that were mostly functional to run the controller normally.  They were getting a busy error every 10 to 30 seconds and then operating normally.  There is a case for simply catching that exception for the caller if the USB can occasionally be saturated.

I am of two minds on how to handle this.  One option is to document that if the caller wants to ensure CircuitPython continues to run an OSError may occur in certain circumstances and they are responsible for wrapping `update` in a try/except.  The other is to simply catch the exception for the caller.  I cannot decide if an error message should be printed at the risk of saturating the Serial output.  Perhaps a debug flag in the constructor could trigger it?

**Comment by fasteddy516** [comment]
I don't believe I've seen this one yet, although I have found that one of my custom controllers based on an ItsyBitsy M4 Express locks up every so often, and when I investigate I find it has dropped back to the REPL.  I'll have to see what happens if I catch exceptions in `send_report` and log them.

In general - particularly given CircuitPython's target audience - I like the idea of JoystickXL gracefully handling the exception by default in order to keep things running, especially if these "USB Busy" events are a regular/expected occurrence.   In the handler, the exception details could be checked to see if it was a "USB Busy" error (so we can keep going) or something else (so we should re-raise the original exception and fail).  I could also see implementing a failure counter so a custom exception could be raised - or an error message printed -  if an inordinate number of 'busy' errors occur within a certain update count.

**Comment by fasteddy516** [comment]
I ended up settling for a simple approach in the interest of finally just getting this into a release version.  The `update` method now has an optional `halt_on_error` parameter that defaults to `False`.  This allows `OSError` exceptions to be ignored by default, which should work for most - if not all - users.  In cases where the exception needs to be handled differently or specifically debugged, users can call `update(halt_on_error=True)` in their main loop, and can wrap it in their own try/except if desired.
